/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package crearyborrar;

import highscore.HighScore;
import highscore.HighScoreList;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author mathboy19
 */
public class LauncherJFrame extends javax.swing.JFrame implements ActionListener, ItemListener {

    /**
     * Creates new form LauncherJFrame
     */
    int choice;
    String description = "This is not a gamemode!";
    HighScoreList hsl = new HighScoreList();
    DefaultListModel listmodel = new DefaultListModel(); 

    public LauncherJFrame() {
        initComponents();
        

    }
    
    public void updateFrame() {
        jTextArea1.setText(description);
        hsl.sort();
        List hsa = hsl.getHighScoreArray();
        listmodel.clear();
        for (Iterator iterator = hsa.iterator(); iterator.hasNext();) {
            HighScore element = (HighScore) iterator.next();
            
            String name = element.getName();
            Double dscore = element.getScore();
            String score = Double.toString(dscore);
            
            String hs = new String();
            hs = (name + " - " + score);
            listmodel.addElement(hs);
        
        }
        if(choice == 1) {
            listmodel.addElement(
                    "No HighScores for Classic!");
        }
    }   
    
    
    
    public void readHighScoreFile() {
        hsl.highscorearray.clear();
        switch (choice) {
            case 1:  hsl.load("classic.txt");
                     break;
            case 2:  hsl.load("normal.txt");
                     break;
            case 3:  hsl.load("large.txt");
                     break;
            case 4:  hsl.load("gigantic.txt");
                     break;
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton4 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CrearYBorrar");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("resources/CrearYBorrar.gif")));

        jButton1.setText("Play");
        jButton1.setToolTipText("Play the Game!");
        jButton1.addActionListener(this);

        jLabel1.setText("Gamemode:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pick One!", "Classic", "Normal", "Large", "Gigantic" }));
        jComboBox1.addItemListener(this);

        jButton2.setText("Help");
        jButton2.setToolTipText("Click this to see some info about CrearYBorrar");
        jButton2.addActionListener(this);

        jButton3.setText("Exit");
        jButton3.setToolTipText("Closes the game.");
        jButton3.addActionListener(this);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(10);
        jTextArea1.setRows(5);
        jTextArea1.setText(description);
        jTextArea1.setToolTipText("Highscores for the sepecified gamemode.");
        jScrollPane2.setViewportView(jTextArea1);
        jTextArea1.getAccessibleContext().setAccessibleName("");

        jLabel2.setText("HighScores:");

        jList1.setModel(listmodel);
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(jList1);

        jButton4.setText("Refresh");
        jButton4.setToolTipText("Click this to refresh the description and HighScores");
        jButton4.addActionListener(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 63, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == jButton1) {
            LauncherJFrame.this.jButton1ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton2) {
            LauncherJFrame.this.jButton2ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton3) {
            LauncherJFrame.this.jButton3ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton4) {
            LauncherJFrame.this.jButton4ActionPerformed(evt);
        }
    }

    public void itemStateChanged(java.awt.event.ItemEvent evt) {
        if (evt.getSource() == jComboBox1) {
            LauncherJFrame.this.jComboBox1ItemStateChanged(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        switch (choice) {
            case 1:  CrearYBorrar c1 = new CrearYBorrar();
                     //Threads
                     Thread t1 = new Thread(c1);
                     t1.start();
                     break;
            case 2:  CrearYBorrarNormal c2 = new CrearYBorrarNormal();
                     //Threads
                     Thread t2 = new Thread(c2);
                     t2.start();
                     break;
            case 3:  CrearYBorrarLarge c3 = new CrearYBorrarLarge();
                     //Threads
                     Thread t3 = new Thread(c3);
                     t3.start();
                     break;
            case 4:  CrearYBorrarGigantic c4 = new CrearYBorrarGigantic();
                     //Threads
                     Thread t4 = new Thread(c4);
                     t4.start();
                     break;
            default: JOptionPane.showMessageDialog(null, 
                    "Gamemode Not Supported!", 
                    "Gamemode Error", JOptionPane.ERROR_MESSAGE);
                     break;
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        super.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        JComboBox cb = (JComboBox) evt.getSource();
        String selection = (String) cb.getSelectedItem();
        if ("Pick One!".equals(selection)) {
            choice = 0;
            description = "This is not a gamemode!";
            
            updateFrame();
        } if ("Classic".equals(selection)) {
            choice = 1;
            description = "Classic Mode:"
                    + "\nThe first mode that was"
                    + "\ncoded, it contains some "
                    + "\nglitches."
                    + "\n\n**NOTE: This was the"
                    + "\nOriginal CrearYBorrar** ";
            readHighScoreFile();
            updateFrame();
        } if ("Normal".equals(selection)) {
            choice = 2;
            description = "Normal Mode:"
                    + "\nThe non-glitchy Classic"
                    + "\nmode. Also contains some"
                    + "\nnew features.";
            readHighScoreFile();
            updateFrame();
        } if ("Large".equals(selection)) {
            choice = 3;
            description = "Large Mode:"
                    + "\nBigger than Normal!";
            readHighScoreFile();
            updateFrame();
        } if ("Gigantic".equals(selection)) {
            choice = 4;
            description = "Gigantic Mode:"
                    + "\nTwice the size, twice the"
                    + "\nEnemys!"
                    + "\n*Note: Try clicking in the"
                    + "\nlower right corner of the"
                    + "\nred box to start*";
            readHighScoreFile();
            updateFrame();
        }
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.out.println("String =" + description);
        JOptionPane.showMessageDialog(null, 
                    "Info:"
                    + "\nCreater: Mathboy19"
                    + "\nVersion: 2.0"
                    + "\nFor more information, visit:"
                    + "\nwww.github.com/Mathboy19/CrearYBorrar",
                    "CrearYBorrar Info", JOptionPane.DEFAULT_OPTION);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      readHighScoreFile();
      updateFrame();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        setDefaultLookAndFeelDecorated(true);
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LauncherJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LauncherJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LauncherJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LauncherJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LauncherJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
